apiVersion : apps/v1
kind: Deployment
metadata:
  name: my-web-deployment
  labels:
    app : my-k8s-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      project: temp # label tag for selecting pods
  template:
    metadata:
      labels:
        project: temp # service will look for pods with those labels
    spec:
      containers:
        - name: temp-web
          image: fromme/k8sphptest:latest
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: my-single-pod-service
  labels:
    env : prod
    owner : max
spec:
  type: LoadBalancer
  selector:
    project: temp # select pods with those labels
  ports:
    - name: app-listener
      protocol: TCP
      port: 80 # port on load balancer
      targetPort: 80 # port on pod