version: '3.8'

services:
  db:
    image: postgres:15
    container_name: db_postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_django
    volumes:
      - ./app:/project/app
    ports:
      - "${WEB_PORT}:8000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  pg_data:
