apiVersion: v1
kind: ConfigMap
metadata:
  name: app-configmap
  namespace: default
data:
  DB_NAME: "myprojectDB"
  DB_HOST: "django-app-psql"
  DB_PORT: "5432"
  DJANGO_SETTINGS_MODULE: "app.settings"
