apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: default
  labels:
    app: postgres-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  serviceName: postgres
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: postgres-db
        image: postgres:15
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: DB_NAME
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: DB_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: DB_PASSWORD
        volumeMounts:
        - name: pg-persistent-storage
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: pg-persistent-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: nfs-client
        resources:
          requests:
            storage: 2Gi

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: default
spec:
  clusterIP: None
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432